In [6]:
import numpy as np
from data_prep import features, targets, features_test, targets_test

In [7]:
np.random.seed(21)

In [8]:
def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))

In [9]:
x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

In [10]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)

In [11]:
## Backwards pass
# Calculate output error
error = target - output

# Calculate error term for output layer
output_error_term = output * (1 - output) * error

# Calculate error term for hidden layer
hidden_error_term = hidden_layer_output * (1 - hidden_layer_output) *\
                    weights_hidden_output * output_error_term

# Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output


# Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * np.matmul(x.reshape(x.shape[0],-1), 
                          hidden_error_term.reshape(-1, hidden_error_term.shape[0]))

In [12]:
# Hyperparameters
n_hidden = 2  # number of hidden units
epochs = 900
learnrate = 0.005

n_records, n_features = features.shape
last_loss = None
# Initialize weights
weights_input_hidden = np.random.normal(scale=1 / n_features ** .5,
                                        size=(n_features, n_hidden))
weights_hidden_output = np.random.normal(scale=1 / n_features ** .5,
                                         size=n_hidden)

for e in range(epochs):
    del_w_input_hidden = np.zeros(weights_input_hidden.shape)
    del_w_hidden_output = np.zeros(weights_hidden_output.shape)
    for x, y in zip(features.values, targets):
        ## Forward pass ##
        # Calculate the output
        print("x:", x.shape)
        hidden_input = np.matmul(x, weights_input_hidden)
        hidden_output = sigmoid(hidden_input)
        output = sigmoid(np.matmul(weights_hidden_output, hidden_output))
        ## Backward pass ##
        # Calculate the network's prediction error
        error = y - output

        # Calculate error term for the output unit
        output_error_term = output * (1 - output) * error
        print("output_error_term:", output_error_term.shape)
        ## propagate errors to hidden layer
        print("weights_hidden_output:", weights_hidden_output.shape)
        # Calculate the hidden layer's contribution to the error
        hidden_error = np.dot(output_error_term, weights_hidden_output)
        # Calculate the error term for the hidden layer
        hidden_error_term = hidden_output * (1 - hidden_output) * hidden_error
        # Update the change in weights
        del_w_hidden_output += learnrate * output_error_term * hidden_output
        del_w_input_hidden += learnrate * np.matmul(x.T, hidden_error_term.T)

    # Update weights  (don't forget to division by n_records or number of samples)
    weights_input_hidden += del_w_input_hidden/n_records
    weights_hidden_output += del_w_hidden_output/n_records

    # Printing out the mean square error on the training set
    if e % (epochs / 10) == 0:
        hidden_output = sigmoid(np.dot(x, weights_input_hidden))
        out = sigmoid(np.dot(hidden_output,
                             weights_hidden_output))
        loss = np.mean((out - targets) ** 2)

        if last_loss and last_loss < loss:
            print("Train loss: ", loss, "  WARNING - Loss Increasing")
        else:
            print("Train loss: ", loss)
        last_loss = loss

# Calculate accuracy on test data
hidden = sigmoid(np.dot(features_test, weights_input_hidden))
out = sigmoid(np.dot(hidden, weights_hidden_output))
predictions = out > 0.5
accuracy = np.mean(predictions == targets_test)
print("Prediction accuracy: {:.3f}".format(accuracy))


x: (6,)
output_error_term: ()
weights_hidden_output: (2,)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 6)

In [14]:
# Hyperparameters
n_hidden = 2  # number of hidden units
epochs = 900
learnrate = 0.005

n_records, n_features = features.shape
last_loss = None
# Initialize weights
weights_input_hidden = np.random.normal(scale=1 / n_features ** .5,
                                        size=(n_features, n_hidden))
weights_hidden_output = np.random.normal(scale=1 / n_features ** .5,
                                         size=n_hidden)

for e in range(epochs):
    del_w_input_hidden = np.zeros(weights_input_hidden.shape)
    del_w_hidden_output = np.zeros(weights_hidden_output.shape)
    for x, y in zip(features.values, targets):
        ## Forward pass ##
        # TODO: Calculate the output
        print("x:", x.shape)
        hidden_input = np.dot(x, weights_input_hidden)
        hidden_output = sigmoid(hidden_input)

        output = sigmoid(np.dot(hidden_output,
                                weights_hidden_output))

        ## Backward pass ##
        # TODO: Calculate the network's prediction error
        error = y - output

        # TODO: Calculate error term for the output unit
        output_error_term = error * output * (1 - output)
        print("output_error_term:", output_error_term.shape)
        ## propagate errors to hidden layer
        print("weights_hidden_output:", weights_hidden_output.shape)
        # TODO: Calculate the hidden layer's contribution to the error
        hidden_error = np.dot(output_error_term, weights_hidden_output)

        # TODO: Calculate the error term for the hidden layer
        hidden_error_term = hidden_error * hidden_output * (1 - hidden_output)

        # TODO: Update the change in weights
        del_w_hidden_output += output_error_term * hidden_output
        del_w_input_hidden += hidden_error_term * x[:, None]

    # TODO: Update weights
    weights_input_hidden += learnrate * del_w_input_hidden / n_records
    weights_hidden_output += learnrate * del_w_hidden_output / n_records

    # Printing out the mean square error on the training set
    if e % (epochs / 10) == 0:
        hidden_output = sigmoid(np.dot(x, weights_input_hidden))
        out = sigmoid(np.dot(hidden_output,
                             weights_hidden_output))
        loss = np.mean((out - targets) ** 2)

        if last_loss and last_loss < loss:
            print("Train loss: ", loss, "  WARNING - Loss Increasing")
        else:
            print("Train loss: ", loss)
        last_loss = loss

# Calculate accuracy on test data
hidden = sigmoid(np.dot(features_test, weights_input_hidden))
out = sigmoid(np.dot(hidden, weights_hidden_output))
predictions = out > 0.5
accuracy = np.mean(predictions == targets_test)
print("Prediction accuracy: {:.3f}".format(accuracy))


x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output_error_term: ()
weights_hidden_output: (2,)
x: (6,)
output

KeyboardInterrupt: 

In [20]:
a = np.random.randn(2,1)

In [21]:
b = np.random.randn(2,1)

In [23]:
a, b

(array([[ 0.48036943],
        [-1.4273776 ]]),
 array([[-0.33326642],
        [ 0.74730849]]))

In [22]:
a * b

array([[-0.160091  ],
       [-1.06669141]])